# Generated by Django 4.2.7 on 2023-11-07 07:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=255)),
                ('image', models.ImageField(blank=True, default='static/images/products/placeholder.png', null=True, upload_to='static/images/products/')),
                ('price', models.DecimalField(decimal_places=2, max_digits=50)),
                ('inventory', models.DecimalField(decimal_places=3, max_digits=50)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.category')),
            ],
        ),
    ]
